In [6]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

**Series is 1D and Dataframes are 2D objects** 
- but why?
- And what exactly is index?

In [2]:
# can we have multiple index ? let's try

index_val=[('cse',2019),('cse',2020),('cse',2021),('cse',2022),('cse',2019),('cse',2020),('cse',2021),('cse',2022)]
a=pd.Series([1,2,3,4,5,6,7,8],index=index_val)
a

(cse, 2019)    1
(cse, 2020)    2
(cse, 2021)    3
(cse, 2022)    4
(cse, 2019)    5
(cse, 2020)    6
(cse, 2021)    7
(cse, 2022)    8
dtype: int64

### how to create multiindex object
- 1=pd.MultiIndex.from_tuples()
- 2=pd.MultiIndex.from_product()

In [3]:
# 1=pd.MultiIndex.from_tuples()
index_val=[('cse',2019),('cse',2020),('cse',2021),('cse',2022),('cse',2019),('cse',2020),('cse',2021),('cse',2022)]
multiindex=pd.MultiIndex.from_tuples(index_val)
multiindex.levels[1]

Index([2019, 2020, 2021, 2022], dtype='int64')

In [9]:

# 2=pd.MultiIndex.from_product()
multiindex=pd.MultiIndex.from_product([['cse','ece'],[2019,2020,2021,2022]])

In [12]:
s=pd.Series([1,2,3,4,5,6,7,8],index=multiindex)
s

cse  2019    1
     2020    2
     2021    3
     2022    4
ece  2019    5
     2020    6
     2021    7
     2022    8
dtype: int64

In [16]:
temp=s.unstack()
temp

     2019  2020  2021  2022
cse     1     2     3     4
ece     5     6     7     8

In [17]:
temp.stack()

cse  2019    1
     2020    2
     2021    3
     2022    4
ece  2019    5
     2020    6
     2021    7
     2022    8
dtype: int64

In [18]:
# multiindex dataframe

branch_df1=pd.DataFrame(
    [
        [1,2],
        [3,4],
        [5,6],
        [7,8],
        [9,10],
        [11,12],
        [13,14],
        [15,16],
    ],
    index=multiindex,
    columns=['avg_package','students']
)

branch_df1

          avg_package  students
cse 2019            1         2
    2020            3         4
    2021            5         6
    2022            7         8
ece 2019            9        10
    2020           11        12
    2021           13        14
    2022           15        16

In [20]:
branch_df1.loc['ece']

      avg_package  students
2019            9        10
2020           11        12
2021           13        14
2022           15        16